### ISSUE TITLE
Ajouter des indicateurs de fiabilité des sources dans la SERP ?

### ISSUE THREAD

**Issue by francoislassagne** [fonzo14/flint-pages#1]
Hello la Flint Team - et bravo à Benoît pour cette enthousiasmante et vivifiante initiative. Du code, de l'esprit critique, et de l'éditorialisation, trio attendu, trio à soigner :)

Première utilisation du proto ce 2/4/2020, une évidence: en cherchant un mot seul ("déconfinement", j'ai fait simple), le moteur retourne 14 résultats, pas davantage. Majoritairement des article de sites de presse, une vidéo ou deux. Mais aucune information sur la hiérarchie de cette sélection: le 1e résultat (position 1 de la SERP) est-il le plus fiable ? (et selon quels critères alors ?) ? Le plus populaire ? Le plus dense en informations ? ... 

A suivre,

keep up the good work !

François Lassagne, langagemachine.fr

**Comment by benoitraphael** [comment]
Hello François ! Merci pour cette remarque, très pertinente. Elle pose en fait la question de la transparence de l'algorithme : pourquoi voit-on cet article plutôt qu'un autre, quels sont les critères de sélection etc.
Je vais te répondre sur ce point, mais ta remarque nous amène à penser qu'il faut aller un peu plus loin. Donc on va mettre ça dans la reflexion collective :)

- Le classement correspond à un score de qualité déterminé par l'IA (c'est le fruit du travail de ces 4 dernieres années). Pas de critère entrés, c'est du machine learning, le robot détermine ses propres critères mathématiquement si tu veux. Mais il appuie ses calculs sur l'observation de plus de 20.000 experts sur plusieurs millions de contenus depuis quelques années, plus l'observation des utilisateurs de Flint et des clients Flint qui entrainent des robots spécialisés. C'est tout à fait améliorable.

Ensuite, et c'est là où on peut aussi améliorer : le classement se fait sur une semaine, pour l'instant. 

Je conclue de tout ça que , dans un premier temps, on devrait rendre visible ce score et l'expliquer (voire en débattre!) et donner la possiblité de trier par 24h / semaine / mois pas exemple.

**Comment by llbash** [comment]
Hello,
Bravo pour ce travail et toutes les bonnes nouvelles reçues !
Je viens dans cette discussion parce que toutes les autres concernent des suggestions de liens. Peut-être faudrait-il les re-router quelque part avec un simple formulaire sur le site et conserver GitHub pour un échange...

Je confirme le problème de manque de hiérarchie dans l'information et aussi malheureusement un manque de qualité dans cette information, le pire étant atteint dans les vidéos. (Peut-être un vote des lecteurs pour valider ou pas une info pourrait aider ?)

Ce matin j'ai voulu savoir quel était l'avancée des travaux autour d'une app de traçage de la pandémie qui s'appuierai sur les données géolocalisées fournies par tous (sur le mode du volontariat). J'ai fait cette recherche sur Google et j'ai eu une assez bonne vision de l'état de l'art. J'ai fait la même recherche sur la plateforme (sans nom) et le résultat a été très... flou.

Sinon la partie "Indispensable" est très pertinente et malheureusement c'est la plus aride, une présentation plus attractive serait un plus.

Le Factchecking gagnerai a être plus hiérarchisé pour trouver facilement les preuves répondant aux infos bidons usuelles. Une approche par question ou comme une sorte de FAQ.

Oups je ne vais pas vous submerger à la première visite, je vais en garder un peu pour les jours suivants !

**Comment by benoitraphael** [comment]
Très bonne idée, on essaie de trouver une solution :)
