### ISSUE TITLE
Notation des sources

### ISSUE THREAD

**Issue by leyronnas** [fonzo14/flint-pages#11]
Hello,

Merci pour tout le travail sur Flint, que je suis depuis quelques années !
À l'instar des courriels, pourrait-on imaginer sur la plateforme un système d'appréciation des sources / sites ?
En l'occurrence, à la recherche https://flint.media/news/search?u=Covid-19&q=raoult , le second résultat est une publication du mediapourtous, sourcé par l'UPR (http://lemediapourtous.fr/virage-a-180-sur-lusage-de-la-chloroquine-le-gouvernement-donne-raison-au-professeur-raoult) -> deux organes douteux dans leur manière de traiter et relayer l'information. Il s'agit d'une opinion de ma part j'en ai conscience, je peux la détailler, mais je pense mon opinion importe peu ici ; il s'agit plutôt de comment noter la pertinence d'une info pour améliorer les robots par le collectif.

Merci d'avance ;-)
Guillaume

**Comment by benoitraphael** [comment]
Oui, on se pose la question. On travaille sur un indicateur de "validation" scientifique... 
Merci !
