### ISSUE TITLE
Partage article Bruno Latour + aide à l'auto-description

### ISSUE THREAD

**Issue by CatherineWeinling** [fonzo14/flint-pages#22]
Bonjour,
Je prends la liberté de partager l'article de Bruno Latour ici.
Son "aide à l'auto-description" m'interpelle, "ce n'est ni un questionnaire, ni un sondage", je l’interprète comme une base de réflexion à mener individuellement et à partager généreusement, du "faire commun" pour inventer un nouveau paradigme.
Bonne soirée,
Catherine

Source : aoc-médias
Rubrique SOCIÉTÉ
Titre :  Imaginer les gestes-barrières contre le retour à la production d’avant-crise
Par Bruno Latour

PHILOSOPHE ET SOCIOLOGUE
Si tout est arrêté, tout peut être remis en cause, infléchi, sélectionné, trié, interrompu pour de bon ou au contraire accéléré. L’inventaire annuel, c’est maintenant qu’il faut le faire. A la demande de bon sens : « Relançons le plus rapidement possible la production », il faut répondre par un cri : « Surtout pas ! ». La dernière des choses à faire serait de reprendre à l’identique tout ce que nous faisions avant.

Il y a peut-être quelque chose d’inconvenant à se projeter dans l’après-crise alors que le personnel de santé est, comme on dit, « sur le front », que des millions de gens perdent leur emploi et que beaucoup de familles endeuillées ne peuvent même pas enterrer leurs morts. Et pourtant, c’est bien maintenant qu’il faut se battre pour que la reprise économique, une fois la crise passée, ne ramène pas le même ancien régime climatique contre lequel nous essayions jusqu’ici, assez vainement, de lutter.

En effet, la crise sanitaire est enchâssée dans ce qui n’est pas une crise – toujours passagère – mais une mutation écologique durable et irréversible. Si nous avons de bonne chance de « sortir » de la première, nous n’en avons aucune de « sortir » de la seconde. Les deux situations ne sont pas à la même échelle, mais il est très éclairant de les articuler l’une sur l’autre. En tout cas, ce serait dommage de ne pas se servir de la crise sanitaire pour découvrir d’autres moyens d’entrer dans la mutation écologique autrement qu’à l’aveugle.

La première leçon du coronavirus est aussi la plus stupéfiante : la preuve est faite, en effet, qu’il est possible, en quelques semaines, de suspendre partout dans le monde et au même moment, un système économique dont on nous disait jusqu’ici qu’il était impossible à ralentir ou à rediriger. À tous les arguments des écologiques sur l’infléchissement de nos modes de vie, on opposait toujours l’argument de la force irréversible du « train du progrès » que rien ne pouvait faire sortir de ses rails, « à cause », disait-on, « de la globalisation ». Or, c’est justement son caractère globalisé qui rend si fragile ce fameux développement, susceptible au contraire de freiner puis de s’arrêter d’un coup.

En effet, il n’y a pas que les multinationales ou les accords commerciaux ou internet ou les tour operators pour globaliser la planète : chaque entité de cette même planète possède une façon bien à elle d’accrocher ensemble les autres éléments qui composent, à un moment donné, le collectif. Cela est vrai du CO2 qui réchauffe l’atmosphère globale par sa diffusion dans l’air ; des oiseaux migrateurs qui transportent de nouvelles formes de grippe ; mais cela est vrai aussi, nous le réapprenons douloureusement, du coronavirus dont la capacité à relier « tous les humains » passe par le truchement apparemment inoffensif de nos divers crachotis. A globalisateur, globalisateur et demi : question de resocialiser des milliards d’humains, les microbes se posent un peu là !

Cette pause soudaine dans le système de production globalisée, il n’y a pas que les écologistes pour y voir une occasion formidable d’avancer leur programme d’atterrissage.

D’où cette découverte incroyable : il y avait bien dans le système économique mondial, caché de tous, un signal d’alarme rouge vif avec une bonne grosse poignée d’acier trempée que les chefs d’État, chacun à son tour, pouvaient tirer d’un coup pour stopper « le train du progrès » dans un grand crissement de freins. Si la demande de virer de bord à 90 degrés pour atterrir sur terre paraissait encore en janvier une douce illusion, elle devient beaucoup plus réaliste : tout automobiliste sait que pour avoir une chance de donner un grand coup de volant salvateur sans aller dans le décor, il vaut mieux avoir d’abord ralenti…

Malheureusement, cette pause soudaine dans le système de production globalisée, il n’y a pas que les écologistes pour y voir une occasion formidable d’avancer leur programme d’atterrissage. Les globalisateurs, ceux qui depuis le mitan du XXe siècle ont inventé l’idée de s’échapper des contraintes planétaires, eux aussi, y voient une chance formidable de rompre encore plus radicalement avec ce qui reste d’obstacles à leur fuite hors du monde. L’occasion est trop belle, pour eux, de se défaire du reste de l’État-providence, du filet de sécurité des plus pauvres, de ce qui demeure encore des réglementations contre la pollution, et, plus cyniquement, de se débarrasser de tous ces gens surnuméraires qui encombrent la planète[1].

N’oublions pas, en effet, que l’on doit faire l’hypothèse que ces globalisateurs sont conscients de la mutation écologique et que tous leurs efforts, depuis cinquante ans, consistent en même temps à nier l’importance du changement climatique, mais aussi à échapper à ses conséquences en constituant des bastions fortifiés de privilèges qui doivent rester inaccessibles à tous ceux qu’il va bien falloir laisser en plan. Le grand rêve moderniste du partage universel des « fruits du progrès », ils ne sont pas assez naïfs pour y croire, mais, ce qui est nouveau, ils sont assez francs pour ne même pas en donner l’illusion. Ce sont eux qui s’expriment chaque jour sur Fox News et qui gouvernent tous les États climato-sceptiques de la planète de Moscou à Brasilia et de New Delhi à Washington en passant par Londres.

Si tout est arrêté, tout peut être remis en cause.

Ce qui rend la situation actuelle tellement dangereuse, ce n’est pas seulement les morts qui s’accumulent chaque jour davantage, c’est la suspension générale d’un système économique qui donne donc à ceux qui veulent aller beaucoup plus loin dans la fuite hors du monde planétaire, une occasion merveilleuse de « tout remettre en cause ». Il ne faut pas oublier que ce qui rend les globalisateurs tellement dangereux, c’est qu’ils savent forcément qu’ils ont perdu, que le déni de la mutation climatique ne peut pas durer indéfiniment, qu’il n’y a plus aucune chance de réconcilier leur « développement » avec les diverses enveloppes de la planète dans laquelle il faudra bien finir par insérer l’économie. C’est ce qui les rend prêts à tout tenter pour extraire une dernière fois les conditions qui vont leur permettre de durer un peu plus longtemps et de se mettre à l’abri eux et leurs enfants. « L’arrêt de monde », ce coup de frein, cette pause imprévue, leur donne une occasion de fuir plus vite et plus loin qu’ils ne l’auraient jamais imaginé[2]. Les révolutionnaires, pour le moment, ce sont eux.

C’est là que nous devons agir. Si l’occasion s’ouvre à eux, elle s’ouvre à nous aussi. Si tout est arrêté, tout peut être remis en cause, infléchi, sélectionné, trié, interrompu pour de bon ou au contraire accéléré. L’inventaire annuel, c’est maintenant qu’il faut le faire. A la demande de bon sens : « Relançons le plus rapidement possible la production », il faut répondre par un cri : « Surtout pas ! ». La dernière des choses à faire serait de reprendre à l’identique tout ce que nous faisions avant.

Par exemple, l’autre jour, on présentait à la télévision un fleuriste hollandais, les larmes aux yeux, obligé de jeter des tonnes de tulipes prêtes à l’envoi qu’il ne pouvait plus expédier par avion dans le monde entier faute de client. On ne peut que le plaindre, bien sûr ; il est juste qu’il soit indemnisé. Mais ensuite la caméra reculait montrant que ses tulipes, il les fait pousser hors-sol sous lumière artificielle avant de les livrer aux avions cargo de Schiphol dans une pluie de kérosène ; de là, l’expression d’un doute : « Mais est-il bien utile de prolonger cette façon de produire et de vendre ce type de fleurs ? ».

Nous devenons d’efficaces interrupteurs de globalisation.

De fil en aiguille, si nous commençons, chacun pour notre compte, à poser de telles questions sur tous les aspects de notre système de production, nous devenons d’efficaces interrupteurs de globalisation – aussi efficaces, millions que nous sommes, que le fameux coronavirus dans sa façon bien à lui de globaliser la planète. Ce que le virus obtient par d’humbles crachotis de bouches en bouches – la suspension de l’économie mondiale –, nous commençons à l’imaginer par nos petits gestes insignifiants mis, eux aussi, bout à bout : à savoir la suspension du système de production. En nous posant ce genre de questions, chacun d’entre nous se met à imaginer des gestes barrières mais pas seulement contre le virus : contre chaque élément d’un mode de production dont nous ne souhaitons pas la reprise.

C’est qu’il ne s’agit plus de reprendre ou d’infléchir un système de production, mais de sortir de la production comme principe unique de rapport au monde. Il ne s’agit pas de révolution, mais de dissolution, pixel après pixel. Comme le montre Pierre Charbonnier, après cent ans de socialisme limité à la seule redistribution des bienfaits de l’économie, il serait peut-être temps d’inventer un socialisme qui conteste la production elle-même. C’est que l’injustice ne se limite pas à la seule redistribution des fruits du progrès, mais à la façon même de faire fructifier la planète. Ce qui ne veut pas dire décroître ou vivre d’amour ou d’eau fraîche, mais apprendre à sélectionner chaque segment de ce fameux système prétendument irréversible, de mettre en cause chacune des connections soi-disant indispensables, et d’éprouver de proche en proche ce qui est désirable et ce qui a cessé de l’être.

D’où l’importance capitale d’utiliser ce temps de confinement imposé pour décrire, d’abord chacun pour soi, puis en groupe, ce à quoi nous sommes attachés ; ce dont nous sommes prêts à nous libérer ; les chaînes que nous sommes prêts à reconstituer et celles que, par notre comportement, nous sommes décidés à interrompre[3]. Les globalisateurs, eux, semblent avoir une idée très précise de ce qu’ils veulent voir renaître après la reprise : la même chose en pire, industries pétrolières et bateaux de croisière géants en prime. C’est à nous de leur opposer un contre-inventaire. Si en un mois ou deux, des milliards d’humains sont capables, sur un coup de sifflet, d’apprendre la nouvelle « distance sociale », de s’éloigner pour être plus solidaires, de rester chez soi pour ne pas encombrer les hôpitaux, on imagine assez bien la puissance de transformation de ces nouveaux gestes-barrières dressés contre la reprise à l’identique, ou pire, contre un nouveau coup de butoir de ceux qui veulent échapper pour de bon à l’attraction terrestre.

Un outil pour aider au discernement
Comme il est toujours bon de lier un argument à des exercices pratiques, proposons aux lecteurs d’essayer de répondre à ce petit inventaire. Il sera d’autant plus utile qu’il portera sur une expérience personnelle directement vécue. Il ne s’agit pas seulement d’exprimer une opinion qui vous viendrait à l’esprit, mais de décrire une situation et peut-être de la prolonger par une petite enquête. C’est seulement par la suite, si vous vous donnez les moyens de combiner les réponses pour composer le paysage créé par la superposition des descriptions, que vous déboucherez sur une expression politique incarnée et concrète — mais pas avant.

Attention : ceci n’est pas un questionnaire, il ne s’agit pas d’un sondage. C’est une aide à l’auto-description*.

Il s’agit de faire la liste des activités dont vous vous sentez privés par la crise actuelle et qui vous donnent la sensation d’une atteinte à vos conditions essentielles de subsistance. Pour chaque activité, pouvez-vous indiquer si vous aimeriez que celles-ci reprennent à l’identique (comme avant), mieux, ou qu’elles ne reprennent pas du tout. Répondez aux questions suivantes :

Question 1 : Quelles sont les activités maintenant suspendues dont vous souhaiteriez qu’elles ne reprennent pas ?

Question 2 : Décrivez a) pourquoi cette activité vous apparaît nuisible/ superflue/ dangereuse/ incohérente ; b) en quoi sa disparition/ mise en veilleuse/ substitution rendrait d’autres activités que vous favorisez plus facile/ plus cohérente ? (Faire un paragraphe distinct pour chacune des réponses listées à la question 1.)

Question 3 : Quelles mesures préconisez-vous pour que les ouvriers/ employés/ agents/ entrepreneurs qui ne pourront plus continuer dans les activités que vous supprimez se voient faciliter la transition vers d’autres activités ?

Question 4 : Quelles sont les activités maintenant suspendues dont vous souhaiteriez qu’elles se développent/ reprennent ou celles qui devraient être inventées en remplacement ?

Question 5 : Décrivez a) pourquoi cette activité vous apparaît positive ; b) comment elle rend plus faciles/ harmonieuses/ cohérentes d’autres activités que vous favorisez ; et c) permettent de lutter contre celles que vous jugez défavorables ? (Faire un paragraphe distinct pour chacune des réponses listées à la question 4.)

Question 6 : Quelles mesures préconisez-vous pour aider les ouvriers/ employés/ agents/ entrepreneurs à acquérir les capacités/ moyens/ revenus/ instruments permettant la reprise/ le développement/ la création de cette activité ?

(Trouvez ensuite un moyen pour comparer votre description avec celles d’autres participants. La compilation puis la superposition des réponses devraient dessiner peu à peu un paysage composé de lignes de conflits, d’alliances, de controverses et d’oppositions.)

 

[1] Voir l’article sur les lobbyistes déchaînés aux Etats-Unis par Matt Stoller, « The coronavirus relief bill could turn into a corporate coup if we aren’t careful », The Guardian, 24.03.20.

[2] Danowski, Deborah, de Castro, Eduardo Viveiros, « L’arrêt de monde », in De l’univers clos au monde infini (textes réunis et présentés). Ed. Hache, Emilie. Paris, Editions Dehors, 2014. 221-339.

[3] L’auto-description reprend la procédure des nouveaux cahiers de doléance suggérés dans Bruno Latour, Où atterrir ? Comment s’orienter en politique. Paris, La Découverte, 2017 et développés depuis par le consortium Où atterrir http://www.bruno-latour.fr/fr/node/841.html

L’auto-description reprend la procédure des nouveaux cahiers de doléance suggérés dans Bruno Latour, Où atterrir ? Comment s’orienter en politique. Paris, La Découverte, 2017 et développés depuis par un groupe d’artistes et de chercheurs.

**Comment by benoitraphael** [comment]
Merci !
