### ISSUE TITLE
Search / Factcheck / Solutions

### ISSUE THREAD

**Issue by Siffleure** [fonzo14/flint-pages#23]
Merci pour cet espace d'expression libre :)

### Recherches

Il serait intéressant de pouvoir sauvegarder ses propres recherches, pour en faire des sujets d'intérêt et ainsi y revenir régulièrement.

### Hashtags

Et si on pouvait créer ses propres hashtags, afin d'enrichir petit à petit la classification des articles ?

### Fact-checking

Rubrique très intéressante. Je trouverais très pratique de disposer d'une rubrique Questions en suspens, c'est à dire : tout ce qu'on sait qu'on ne sait pas.

Ce serait également précieux de pouvoir distinguer ce qui est établi de ce qui est seulement probable, sans preuves définitives.

On pourrait imaginer une palette de couleurs en fonction du degré d'ignorance sur chaque question. Avec bien sûr une évolution dans le temps, selon l'avancée des connaissances.

### Solutions

Et si on disposait d'une rubrique sur les choses qui marchent, autrement dit les solutions éprouvées ici ou ailleurs ?
Solutions sanitaires, médicales, économiques, solidaires.

**Comment by benoitraphael** [comment]
Merci, très bonnes idées, on se met dessus !
